### ISSUE TITLE
Support for "compounds"?

### ISSUE THREAD

**Issue by ben-clayton** [microsoft/VSDebugAdapterHost#13]
Hello,

I'm currently evaluating suitability of DAP as method for implementing "mixed-mode" debugging - i.e. the ability to combine multiple debugger end points into a single debug session.
An example usage of this would be the ability to attach to a regular C++ debugger along with another DAP end-point that provides a script interpreter debugger. Ideally, we'd be able to set breakpoints in both C++ and the script source and hop between both in a seamless way.

VSCode supports [compound launch configurations](https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations) which provides one way to achieve this. However, as far as I can tell VS does not support this (nor any other IDE).

I'm fairly new to all of this, but my understanding so far is that the VS's DAP implementation is built in 3-tiers:

1. The [`Microsoft.VisualStudio.Shared.VsCodeDebugProtocol`](https://www.nuget.org/packages/Microsoft.VisualStudio.Shared.VsCodeDebugProtocol)
This contains the Visual Studio debug engine integration and the DAP serialization code. Closed source?

2. [The `EngineLauncher` VS extension](https://github.com/microsoft/VSDebugAdapterHost/tree/master/src/tools/EngineLauncher)
Part of this open source repo.
Talks to the `Visual Studio Debug Adapter Host` via the magic [`DebugAdapterHostPackageCmdSet`](https://github.com/microsoft/VSDebugAdapterHost/blob/master/src/tools/EngineLauncher/LaunchEngineCommand.cs#L90) GUID.
Implements a UI in VS to pick the [debug adapter](https://github.com/microsoft/VSDebugAdapterHost/tree/master/src/sample/SampleDebugAdapter) to launch.

3. The [`Debug Adapter`](https://github.com/microsoft/VSDebugAdapterHost/tree/master/src/sample/SampleDebugAdapter) implementations.
These are the debugger executables that talk DAP.

Is that right?

I'm completely spitballing here, but off the top of my head, these are the ways I've considered solving this:

**(a)** I could implement a new debug adapter that wraps two or more downstream debug adapters.

![compound-dbg](https://user-images.githubusercontent.com/11505236/67280720-b2fa6600-f4c5-11e9-960d-d6340679a49d.png)

This rather makes the assumption that the C++ debugger talks DAP, and isn't the native VS debugger (which I assume predates DAP, and talks directly to the IDE).

The existing `EngineLauncher` UI isn't ideal for this, but I've [already seen it is possible](https://github.com/phoityne/hdx4vs/blob/master/HaskellDebugCommand.cs) to replace parts **2.** and **3.** of the stack so a custom interface can be developed.

**(b)** The `Microsoft.VisualStudio.Shared.VsCodeDebugProtocol` is extended to support compound DAP sessions, much like VSCode.

As I haven't seen the source to this package†, I have no idea how much work this would be.

Like **(a)**  this approach clearly will not work with non-DAP debuggers.

**(c)** A new [Visual Studio Debug Engine](https://docs.microsoft.com/en-us/visualstudio/extensibility/debugger/visual-studio-debugger-extensibility?view=vs-2019&redirectedfrom=MSDN) is developed to wrap two or more debug engines.

Similar to (a), but the multiplexing is done lower down the stack. I have no idea whether this would work, and if it is possible, how much work it would be. I'm guessing it would be very difficult if not impossible to implement without the source to `VsCodeDebugProtocol`, or reimplementing the DAP debug engine.
I also have no idea if this approach would allow you to wrap the default VS C++ debugger.

Have you had any thoughts on this? Do you have any recommendations or suggestions?

Many thanks,
Ben

---

† If the `VsCodeDebugProtocol` package is closed source, are there any plans to open source it?

**Comment by andrewcrawley** [comment]
Hi, Ben

Quick note - the EngineLauncher extension is not involved in any real scenarios.  It's strictly a tool to help with testing debug adapters.  In practice, adapters are generally launched by a project system using `IVsDebugger4.LaunchDebugTargets4` - see https://github.com/microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/Project/NodejsProjectLauncher.cs#L280 for an example.

As you noted, VS Code allows you to configure a compound scenario using launch.json.  VS generally doesn't expose configuration like that - instead, it's the job of a project system to set up a compound scenario.  One common example is a web project, which often launches both a web server (with, say, the C# debugger attached) and a browser (with a JS debugger attached).  In both VS and VS Code, this involves two separate processes, each of which has a single debugger attached, and is generally straightforward-ish.

Attaching multiple debuggers to a single process, however, is an extremely complex scenario.  For one thing, most platform debugging APIs only allow one debugger at a time to be attached to a given process.  Setting that aside (maybe the C++ debugger uses the platform debugging API, and the script debugger attaches to a socket), you'll quickly run into issues that require the individual debuggers to be aware of each other.  For instance, let's say you're stopped in some location that has both C++ and script on the callstack, and you want to evaluate a script expression.  The script debugger sends an `evaluate` request via the socket it's attached to, but since the entire process containing the script engine is currently stopped in the debugger with all threads suspended, it won't be able to service the request.  The script debugger would have to collaborate with the C++ debugger to resume the appropriate threads to allow the script engine to run, then do the evaluation (which may end up calling into other C++ code, which may have other breakpoints set), then restore the process state.

This collaboration is likely to be complex enough that rather than having separate C++ and script debuggers, it would be simpler to have a single "C++ and script" debugger.  This is the approach we took with the debugger in VS, which supports debugging C++, C# / VB, and certain kinds of script in a single process, with unified callstacks, breakpoints, etc.

**Comment by ben-clayton** [comment]
Hi Andrew,

Sorry for the delay in replying.

> Quick note - the EngineLauncher extension is not involved in any real scenarios. It's strictly a tool to help with testing debug adapters.

Thank you for the clarification, I had clearly misunderstood this. Thank you also for the example, I'll give this approach a try.

> Attaching multiple debuggers to a single process, however, is an extremely complex scenario

Understood. My example of a script VM wasn't the best one, but let's continue with this for sake of discussion.

> The script debugger sends an evaluate request via the socket it's attached to, but since the entire process containing the script engine is currently stopped in the debugger with all threads suspended, it won't be able to service the request

I guess this is a restriction enforced by Visual Studio's all-threads-or-none break behavior. I have a proof of concept working inside VSCode where I can do just this, by keeping the 'application' threads running (specifically, all we need is the script VM thread running), while having the specific 'script' thread (which performs the `evaluate`) suspended. While my proof of concept demonstrates this is feasible in VSCode, I appreciate your argument for Visual Studio. One way I could imagine to avoid this issue would be to separate out the script VM into a separate process. Not that I'd recommend doing this for this hypothetical scenario.

Unfortunately, I can't go into too many details of my actual use case, but it doesn't actually suffer from this problem.

> This collaboration is likely to be complex enough that rather than having separate C++ and script debuggers, it would be simpler to have a single "C++ and script" debugger

I guess this is the closest match to approach **(c)** described above (except instead of wrapping, you're proposing just building a new bespoke debugger?). It's the approach I was also leaning towards, but doesn't have the works-for-multiple-IDEs elegance of **(a)**.
If I were to implement a new 'integrated debugger', I'm still keen to use the DAP as the protocol to control the VM.

Using Visual Studio's Object Browser, I can see that the `Microsoft.VisualStudio.Shared.VsCodeDebugProtocol` package offers a nice API for talking DAP, and appears simple enough to use without additional documentation (if there is additional documentation though, I'd love to see it!).

Am I right in thinking that all clever secret sauce that makes the Visual Studio DAP debugger work belongs in `Microsoft.VisualStudio.Shared.VsCodeDebugProtocol`? Is there any public documentation I've missed for this? Is there any chance of this being open sourced? Seeing how this was put together would greatly aid in building another debugger implementation.

Thank you ever so much for taking the time to respond to me.

Many thanks,
Ben

**Comment by andrewcrawley** [comment]
Sorry, I didn't intend to suggest writing a new C++ / script debugger from scratch, just pointing out that coordination between debuggers may be required, and the DAP may not be the best choice as a mechanism for that coordination, depending on how complex your scenario is.  DAP is a great option for the external interface, however, since it allows easy hosting in multiple IDEs (subject to certain limitations we've already discussed regarding compatibility with VS 😄)

`Microsoft.VisualStudio.Shared.VsCodeDebugProtocol` is an implementation of the Debug Adapter Protocol.  It provides strongly-typed representations of the protocol messages defined in the DAP schema and some infrastructure to help with serialization / deserialization of messages.  It's not open-source, but you can grab it as a NuGet package here: https://www.nuget.org/packages/Microsoft.VisualStudio.Shared.VsCodeDebugProtocol/  There isn't any online documentation, but the NuGet package includes method-level documentation that will show up in the IDE.  The interesting classes are likely `DebugProtocolClient` / `DebugProtocolHost`, which implement sending / receiving of messages for a debug adapter and a debug adapter host (e.g. an IDE) respectively, and `DebugAdapterBase` / `DebugAdapterHostBase`, which are intended as base classes for debug adapters and hosts.  For examples of debug adapters based on `DebugAdapterBase`, you can check out either [SampleDebugAdapter](https://github.com/microsoft/VSDebugAdapterHost/blob/master/src/sample/SampleDebugAdapter/SampleDebugAdapter.cs) or [MIEngine](https://github.com/microsoft/MIEngine/blob/master/src/OpenDebugAD7/AD7DebugSession.cs), and feel free to ping me / file issues if you have questions or run into problems.

Support for running DAP-based debuggers in VS is provided by a debug engine that implements the VS debugging API (AD7) and translates those calls into DAP messages.  This is implemented in a separate assembly that is not redistributed outside of the product, but it uses the `DebugAdapterHostBase` class mentioned above to handle the DAP side of things.

**Comment by ben-clayton** [comment]
Thank you Andrew for all your help.
I'm sure this is enough information for me to go on.

Thanks again,
Ben
