### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Logopher** [Microsoft/VSDebugAdapterHost#33]
Currently only Chrome, Edge, and IE are supported as debug targets. Are there any plans to support Firefox?

I've been launching my server Swagger in Firefox and my client in Edge for a while now, and just now found out why.

Relevant:

https://learn.microsoft.com/en-us/visualstudio/javascript/debug-nodejs?view=vs-2022

https://stackoverflow.com/questions/74844855/error-converting-value-firefox-to-type-microsoft-visualstudio-webclient-diagn

**Comment by gregg-miskelly** [comment]
Hi @Logopher, there is no one who monitors this GitHub who would have any idea. I would suggest filing a suggestion ticket so that it can get routed to the appropriate team, and so other customers can vote for your suggestion if other folks would like to see Firefox debugging in Visual Studio. 

To do so, from Visual Studio, go to "Help->Send Feedback->Suggest a Feature", and submit a ticket suggesting that Visual Studio support Firefox debugging.
