### ISSUE TITLE
mouse hover doesn't show hint.

### ISSUE THREAD

**Issue by phoityne** [Microsoft/VSDebugAdapterHost#6]
Hello.
I'm trying to run Haskell debug adapter on VisualStudio2017.

Does VS have a functionality that shows type, value or any hint by mouse hover?
[VSCode does](https://github.com/phoityne/hdx4vs/issues/2#issuecomment-408596122). It sends evalute request with hover and show the result on the UI.

I checked request log from VSDebugAdapterHost in the debug adapter's log, but no evaluate request was arrived.

Any advice will be appreciated.
Best Regards.

**Comment by gregg-miskelly** [comment]
@phoityne The issue is that in Visual Studio data tips are a combined language service and debugger feature -- the language service gets the "on hover" event from the editor, and decides which text range should be evaluated. Where in VS Code is it just a debugger feature, and the IDE itself guesses would a good range of text should be.

So short answer: You will need at least a very minimal language service to get data tips to work.

**Comment by phoityne** [comment]
Thank you for the information.
I understand why the mouse hover does not work with debug adapter(alone) in Visual Studio.
